# /* ******************************************************************** */
# /* # This file was generated by a call to 'CTUtemplate::CTUtemplate()'. */
# /* Author: Marie Roumet                                                 */
# /* Date created: 27.4.2026                                       */
# /* Last update:                                                         */
# /* ******************************************************************** */ 


#' bl_nobs_function
#' 
#' Add Nobs to a gtsummary table of class "tbl_summary" 
#' This function add the Nobs (i.e. number of non-missing data) to a gtsummary table. 
#' Depending on the specified location Nobs will be:
#' (i) added in a new column, 
#' (ii) displayed as statistics alongside the variable name
#' (iii) added after the variable name within the same cell.
#'
#' @param table a gtsummary table of class "tbl_summary"
#' 
#' @param location the location for the Nobs.Can take the following values:
#'   
#'  "col" = Nobs is displayed new column(s) (default)  
#'  
#'  "row" : Nobs is displayed as statistics alongside the variable name. Stats are presented below 
#'   
#'  "var_name": Nobs is added after the variable name within the same cell.This option is only available if the table is not stratified  
#
#' @return a gtsummary table with the Nobs 
#' 
#' @examples
#' #Data
#' data("cancer", package = "survival")#' 
#' cancer <- 
#'  cancer %>% 
#' dplyr::mutate(
#'   sex.factor = factor(sex, levels = c(1,2), labels = c("Female", "Male") ),
#'  yn_var = factor(sex, levels = c(1,2), labels = c("Yes", "No") )
#') %>% 
#'labelled::set_variable_labels (
#'  yn_var = "Yes/no variable",
#'  sex.factor = "Gender",
#'  inst = "Institution code",
#'   time = "Time", 
#'  age = "Age",
#'  ph.ecog = "ECOG score") 
#'  
#' 
#'  # Ex1: stratified table
#'  #. gtsummaty table
#' tab <- 
#'   cancer %>% 
#'   select(sex.factor, yn_var, inst, time,age, ph.ecog) %>% 
#'   gtsummary::tbl_summary(
#'  by=sex.factor,
#'  type = all_continuous() ~ "continuous2",
#'  statistic = all_continuous() ~ c("{median} ({p25}, {p75})", "{min} - {max}"),
#' )  %>% 
#' gtsummary::add_overall() 
#' 
#'  # .Add Nobs gtsummaty table 
#' tab %>%  add_nobs (location = "row")
#' tab %>% add_nobs (location = "col")
#'   
#' # Ex2: un-stratified table 
#' #. gtsummaty table
#' tab <- 
#'   cancer %>% 
#'   select(sex.factor, yn_var, inst, time,age, ph.ecog) %>% 
#'   gtsummary::tbl_summary() 
#'   
#'  # .Add Nobs gtsummaty table 
#'  tab %>%  
#'  add_nobs(location = "var_name")
#' 
#' @export
#' @import dplyr
#' @import gtsummary
#' 

add_nobs <- function(table, location = "col"){
  
  #...........................................----
  # parameters ----
  #...........................................----
  grp <- table$inputs$by 
  data <- table$inputs$data
  by_col <- tab <- temp_na_stat <- variable <- NULL
  #...........................................----
  # Check basic errors / parameters def ----
  #...........................................----
  
  if(  length(grp) != 0 & location == "var_name") {
    stop("ERROR : this location option is only available for stratified tables")
  }
  
  if(class(tab)[1] !=  'tbl_summary'[1] |  class(tab)[2] !='gtsummary'){
    stop("ERROR : table should be a table of class c('tbl_summary', 'gtsummary')" )
  }
  
  #...........................................----
  # Add Nobs in column (default)----
  #...........................................----
  # Add overall Nobs: If overall OR no grouping ----
  
  #. Nobs in a column ----
  if(
    "add_overall" %in% (table$cards  %>% names()) |
    length(grp) == 0
  ){
    table <- table  %>% 
      add_n( col_label = "**Nobs**")
  }
  
  # Add Nobs per groups: if groups----
  if (length(grp) != 0 ) { 
    n_grp <- 
      data  %>% 
      pull (grp)  %>% 
      unique()  %>% 
      length()
    
    #. Nobs in columns ----
    table <- 
      table %>% 
      add_stat (fns = everything() ~ add_by_n  )  %>% 
      modify_header (starts_with("add_n_stat") ~ "**Nobs**") 
    
    for (i in 1:n_grp){
      table <- 
        table  %>% 
        modify_table_body (
          ~ .x %>% 
            relocate (sprintf("add_n_stat_%s",i), 
                             .before = sprintf("stat_%s",i)) 
        )
    }
  }
  
  #**************************----
  # Location == "var_name" ----
  #. Nobs with the variable label
  #**************************----
  if(  length(grp) == 0 & location == "var_name") {
    table <- 
      table  %>% 
      modify_table_body(
        ~ .x %>% 
          mutate( 
            label = case_when(
              row_type !="label" ~ label,
              .default = sprintf("%s, Nobs = %s",label, n)
            )
          )  %>% 
          select(-n)
      )
  } 
  
  #**************************----
  # location == "row" ----
  # for each variable, the first row contains variable name + Nobs 
  # For some variables (e.g. categorical) it is fine. For other we need to integrate a new row
  #**************************----
  
  if( location == "row" ){ 
    
    #Add the stat name ----
    table <- table %>% 
      add_stat_label (location = "column")
    
    # Add a row if needed ----
    table <- 
      table  %>% 
      modify_table_body (
        ~ .x  %>% 
          mutate (
            temp_table = 2,
            temp_row = 1:n(),
            temp_na_stat = rowSums(
              across(starts_with("stat_"), 
                            \(x) ( !is.na(x) ) 
              )
            )
          )
      )
    
    # Create the new rows  with names and Nobs
    b <-  table$table_body  %>% 
      group_by (variable)  %>% 
      slice (1)  %>% 
      ungroup ()  %>% 
      filter (temp_na_stat!=0)  %>% 
      select (-starts_with("stat_"))  %>% 
      mutate ( temp_table =1)
    
    #Add the new rows     
    table <- 
      table  %>% 
      modify_table_body (
        ~ .x  %>% 
          mutate (
            across ( 
              c( starts_with("add_n_"), any_of(c("n", "label") ) ),
              ~ case_when (
                label %in% b$label~ NA ,
                .default=.x
              )   
            ) 
          )  %>% 
          full_join (., b)  %>% 
          arrange (temp_row, temp_table)   %>% 
          select (-starts_with("temp_"))  %>% 
          group_by (variable)  %>% 
          mutate( nl=1:n())  %>% 
          ungroup ()  %>% 
          mutate (row_type = 
                           case_when (
                             nl ==1 ~ "label",
                             nl != 1 & row_type == "label" ~ "level",
                             .default = row_type)
          )  %>% 
          select (-nl)
      )
    
    # Move the Nobs under the stat columns----
    
    if( "add_overall" %in% (table$cards  %>% names()) ) {
      table <- 
        table  %>% 
        modify_table_body (
          ~ .x  %>%   
            mutate(
              stat_0 = 
                case_when(
                  row_type == "label" ~ n,
                  .default = stat_0) 
            )
        )
    }
    
    if( length(grp) != 0 ) {
      
      for (i in 1:n_grp){
        stat <- sprintf("stat_%s",i)
        nstat <- sprintf("add_n_stat_%s",i)
        
        table <- 
          table  %>% 
          modify_table_body(
            ~ .x  %>%   
              mutate(
                "{stat}" := 
                  case_when(
                    row_type == "label" ~ .data[[nstat]],
                    .default =  .data[[stat]]) 
              )
          )
      }
    }
    
    # Move the stats label ----
    table <- 
      table  %>% 
      modify_table_body(
        ~ .x  %>%   
          mutate ( 
            label = case_when(
              row_type!="label" & is.na(label) ~ stat_label,
              row_type!="label" & !is.na(label) ~ label,
              .default= sprintf("%s, Nobs",label)
            )
          )  %>% 
          select( -starts_with("add_n_stat"), -any_of( c("n", "stat_label") ) )
      )
    
  }
  
  #..............................................................----
  #Return ----
  #..............................................................----
  return(table)
}


